# Site settings
title: Growth and Remodeling Tutorial Site
description: A website walking through the FEBio implementation of constrained mixture growth and remodeling.
url: "https://schwarz-e.github.io" # replace with your actual GitHub Pages URL
author: Erica L. Schwarz

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Appearance
show_downloads: false

# Navigation links (appear in header)
navigation:
  - name: Home
    link: /
  - name: GitHub Account
    link: /github-setup/
  - name: Linux Environment
    link: /linux-setup/
  - name: Running MBE
    link: /mbe-simulations/
  - name: Running FSG
    link: /fsg-simulations/
  - name: Post-Processing
    link: /post-processing/

markdown: kramdown
